name: CI/CD

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  buildAndTest:
    name: Build & test App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

        name: Npm cache
      - run: yarn install --frozen-lockfile
        name: Install deps
      - run: yarn lint
        name: Running ESlint
      - run: yarn format
        name: Running Prettier
      - run: yarn test:ci
        name: Running tests
