name: CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  buildAndTest:
    name: Build & test App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      
        name: Installing deps
      - run: yarn install --frozen-lockfile
        name: Running ESlint
      - run: yarn lint
        name: Running Prettier
      - run: yarn prettier
        name: Running tests
      - run: yarn test:ci
